spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  redis:
    port: ${REDIS_MAIL_PORT}
    host: ${REDIS_MAIL_HOST}
  mail:
    host: ${MAIL_HOST} #smtp 서버 주소
    port: ${MAIL_PORT} # 메일 인증서버 포트
    username: ${MAIL_USERNAME} #구글 아이디
    password: ${MAIL_PASSWORD} #구글 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      group-id: ${GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  aws:
    ses:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
      region: ${REGION}
  data:
    redis:
      port: ${REDIS_MAIL_PORT}
      host: ${REDIS_MAIL_HOST}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
server:
  port: ${RESERVATION_SERVER_PORT}

kakao-payment:
  admin-key: ${PAY_ADMIN_KEY}
  cid: TC0ONETIME
  approve-url:  http://localhost:${RESERVATION_SERVER_PORT}/payments/kakaoPaySuccess
  cancel-url: http://localhost:${RESERVATION_SERVER_PORT}/payments/kakaoPayCancel
  fail-url: http://localhost:${RESERVATION_SERVER_PORT}/payments/kakaoPayFail