name: Deploy Backend Modules

on:
  push:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Build each module
      - name: Build escape-search
        run: |
          cd escapeSparta/escape-search
          ./gradlew bootJar

      - name: Build escape-reservation
        run: |
          cd escapeSparta/escape-reservation
          ./gradlew bootJar

      - name: Build escape-manager
        run: |
          cd escapeSparta/escape-manager
          ./gradlew bootJar

      - name: Build escape-core
        run: |
          cd escapeSparta/escape-core
          ./gradlew bootJar

      - name: Build escape-consumer
        run: |
          cd escapeSparta/escape-consumer
          ./gradlew bootJar

      - name: Build escape-admin
        run: |
          cd escapeSparta/escape-admin
          ./gradlew bootJar

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      # Build and push Docker images for each module
      - name: Build and push escape-search Docker image
        run: |
          cd escapesparta/escape-search
          docker build -t escapesparta/escape-search:latest .
          docker push escapesparta/escape-search:latest

      - name: Build and push escape-reservation Docker image
        run: |
          cd escapesparta/escape-reservation
          docker build -t escapesparta/escape-reservation:latest .
          docker push escapesparta/escape-reservation:latest

      - name: Build and push escape-manager Docker image
        run: |
          cd escapesparta/escape-manager
          docker build -t escapesparta/escape-manager:latest .
          docker push escapesparta/escape-manager:latest

      - name: Build and push escape-core Docker image
        run: |
          cd escapesparta/escape-core
          docker build -t escapesparta/escape-core:latest .
          docker push escapesparta/escape-core:latest

      - name: Build and push escape-consumer Docker image
        run: |
          cd escapesparta/escape-consumer
          docker build -t escapesparta/escape-consumer:latest .
          docker push escapesparta/escape-consumer:latest

      - name: Build and push escape-admin Docker image
        run: |
          cd escapesparta/escape-admin
          docker build -t escapesparta/escape-admin:latest .
          docker push escapesparta/escape-admin:latest

      - name: Copy docker-compose file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ec2-user/app"

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /path/to/escapesparta-b13
            docker-compose pull
            docker-compose up -d 
